###############################################################################
#
# Generic
#
###############################################################################
ci/cd:
- .github/workflows/*

infrastructure:
- terraform/**

documentation:
- docs/**/*
- README.md
- ./*.md
